package com.craftingtree.recipedumper.dump;

import com.craftingtree.recipedumper.util.JsonUtil;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class DocsGenerator {
    private DocsGenerator() {
    }

    public static void generate(Path outputRoot, boolean prettyPrint) throws IOException {
        Path docsRoot = outputRoot.resolve("docs");
        Files.createDirectories(docsRoot.resolve("examples"));

        Files.writeString(docsRoot.resolve("README.md"), buildReadme(), StandardCharsets.UTF_8);
        Files.writeString(docsRoot.resolve("schema_raw_notes.md"), buildRawNotes(), StandardCharsets.UTF_8);

        JsonObject schema = buildNormalizedSchema();
        JsonUtil.writeJson(docsRoot.resolve("schema_normalized.json"), schema, prettyPrint);

        Files.writeString(docsRoot.resolve("examples/normalized_example_crafting_shaped.json"), exampleShaped(), StandardCharsets.UTF_8);
        Files.writeString(docsRoot.resolve("examples/normalized_example_create_mixing.json"), exampleCreateMixing(), StandardCharsets.UTF_8);
        Files.writeString(docsRoot.resolve("examples/tag_example.json"), exampleTag(), StandardCharsets.UTF_8);
    }

    private static String buildReadme() {
        return "# Recipe Dump Output\n\n"
                + "This folder is generated by the `/recipe_dump` command at runtime. It captures the **final** recipe set after datapacks and KubeJS scripts are applied.\n\n"
                + "## Contents\n\n"
                + "- `raw/` codec-serialized recipes as Minecraft sees them.\n"
                + "- `normalized/` analysis-friendly normalized recipes (schema v1).\n"
                + "- `tags/` item tag dumps.\n"
                + "- `meta.json` generation metadata and warnings/errors.\n"
                + "- `index.json` listing of all recipes with paths.\n\n"
                + "## Usage\n\n"
                + "Run `/recipe_dump` (or `/recipe_dump recipes` or `/recipe_dump tags`) after datapacks and KubeJS scripts load.\n"
                + "If you reload datapacks with `/reload`, rerun the command to regenerate.\n\n"
                + "## Normalized Schema\n\n"
                + "Each recipe file in `normalized/recipes/...` uses schema version 1.\n"
                + "Ingredients are represented with `kind` values: `item`, `tag`, `any_of`, or `unknown`.\n"
                + "Tags omit the leading `#`, for example `forge:plates/iron`.\n\n"
                + "## Guarantees\n\n"
                + "- Recipes reflect the runtime server `RecipeManager` state.\n"
                + "- Recipes removed by datapacks/KubeJS are not present.\n"
                + "- Tag dumps reflect the active datapack state.\n\n"
                + "## Known Limitations\n\n"
                + "- Custom modded recipe types may only be partially normalized.\n"
                + "- When a recipe cannot be normalized, an empty structure is still emitted with warnings.\n";
    }

    private static String buildRawNotes() {
        return "# Raw Recipe Notes\n\n"
                + "Raw recipe JSON is generated via the recipe serializer codec at runtime.\n"
                + "This means it represents the exact structure Minecraft uses internally after datapack and script processing.\n"
                + "If codec serialization fails, the normalized output still exists and a warning is recorded in `meta.json`.\n";
    }

    private static JsonObject buildNormalizedSchema() {
        JsonObject root = new JsonObject();
        root.addProperty("$schema", "https://json-schema.org/draft/2020-12/schema");
        root.addProperty("title", "NormalizedRecipe");
        root.addProperty("type", "object");
        root.addProperty("description", "Analysis-friendly normalized recipe schema.");
        JsonObject properties = new JsonObject();
        properties.add("schema_version", schemaNumber("Schema version."));
        properties.add("id", schemaString("Recipe id."));
        properties.add("type", schemaString("Recipe type id."));
        properties.add("group", schemaString("Recipe group."));
        properties.add("category", schemaString("Recipe category."));
        properties.add("inputs", schemaArray("Inputs list.", ingredientSchema()));
        properties.add("outputs", schemaArray("Outputs list.", outputSchema()));
        properties.add("byproducts", schemaArray("Byproducts list.", outputSchema()));
        properties.add("processing", processingSchema());
        properties.add("conditions", schemaArray("Conditions list.", schemaString("Condition string.")));
        properties.add("meta", metaSchema());
        root.add("properties", properties);
        root.add("required", JsonUtil.createGson(true).toJsonTree(new String[]{\"schema_version\", \"id\", \"type\", \"inputs\", \"outputs\", \"meta\"}));
        return root;
    }

    private static JsonObject schemaString(String description) {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "string");
        obj.addProperty("description", description);
        return obj;
    }

    private static JsonObject schemaNumber(String description) {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "integer");
        obj.addProperty("description", description);
        return obj;
    }

    private static JsonObject schemaArray(String description, JsonObject items) {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "array");
        obj.addProperty("description", description);
        obj.add("items", items);
        return obj;
    }

    private static JsonObject ingredientSchema() {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "object");
        JsonObject properties = new JsonObject();
        properties.add("kind", schemaString("item|tag|any_of|unknown"));
        properties.add("id", schemaString("Identifier for item or tag."));
        properties.add("count", schemaNumber("Item count."));
        properties.add("options", schemaArray("Options for any_of.", obj));
        obj.add("properties", properties);
        return obj;
    }

    private static JsonObject outputSchema() {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "object");
        JsonObject properties = new JsonObject();
        properties.add("kind", schemaString("item|unknown"));
        properties.add("id", schemaString("Item identifier."));
        properties.add("count", schemaNumber("Output count."));
        properties.add("nbt", new JsonObject());
        obj.add("properties", properties);
        return obj;
    }

    private static JsonObject processingSchema() {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "object");
        JsonObject properties = new JsonObject();
        properties.add("time_ticks", schemaNumber("Processing time in ticks."));
        properties.add("energy", schemaNumber("Energy cost if available."));
        properties.add("heat", schemaString("Heat requirement if available."));
        properties.add("notes", schemaArray("Processing notes.", schemaString(\"Note\")));
        obj.add("properties", properties);
        return obj;
    }

    private static JsonObject metaSchema() {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", "object");
        JsonObject properties = new JsonObject();
        properties.add("origin", schemaString("Origin of data."));
        properties.add("raw_path", schemaString("Raw JSON path."));
        properties.add("serializer", schemaString("Serializer id."));
        properties.add("warnings", schemaArray("Normalization warnings.", schemaString(\"Warning\")));
        obj.add("properties", properties);
        return obj;
    }

    private static String exampleShaped() {
        return "{\n"
                + "  \"schema_version\": 1,\n"
                + "  \"id\": \"minecraft:oak_planks\",\n"
                + "  \"type\": \"minecraft:crafting_shaped\",\n"
                + "  \"group\": \"\",\n"
                + "  \"category\": \"\",\n"
                + "  \"inputs\": [\n"
                + "    { \"kind\": \"item\", \"id\": \"minecraft:oak_log\", \"count\": 1, \"options\": [] }\n"
                + "  ],\n"
                + "  \"outputs\": [\n"
                + "    { \"kind\": \"item\", \"id\": \"minecraft:oak_planks\", \"count\": 4, \"nbt\": null }\n"
                + "  ],\n"
                + "  \"byproducts\": [],\n"
                + "  \"processing\": { \"time_ticks\": null, \"energy\": null, \"heat\": null, \"notes\": [] },\n"
                + "  \"conditions\": [],\n"
                + "  \"meta\": {\n"
                + "    \"origin\": \"runtime\",\n"
                + "    \"raw_path\": \"raw/data/minecraft/recipes/oak_planks.json\",\n"
                + "    \"serializer\": \"minecraft:crafting_shaped\",\n"
                + "    \"warnings\": []\n"
                + "  }\n"
                + "}\n";
    }

    private static String exampleCreateMixing() {
        return "{\n"
                + "  \"schema_version\": 1,\n"
                + "  \"id\": \"create:mixing/example\",\n"
                + "  \"type\": \"create:mixing\",\n"
                + "  \"group\": \"\",\n"
                + "  \"category\": \"\",\n"
                + "  \"inputs\": [\n"
                + "    { \"kind\": \"tag\", \"id\": \"forge:flour\", \"count\": 1, \"options\": [] },\n"
                + "    { \"kind\": \"item\", \"id\": \"minecraft:water_bucket\", \"count\": 1, \"options\": [] }\n"
                + "  ],\n"
                + "  \"outputs\": [\n"
                + "    { \"kind\": \"item\", \"id\": \"create:dough\", \"count\": 1, \"nbt\": null }\n"
                + "  ],\n"
                + "  \"byproducts\": [],\n"
                + "  \"processing\": { \"time_ticks\": null, \"energy\": null, \"heat\": null, \"notes\": [] },\n"
                + "  \"conditions\": [],\n"
                + "  \"meta\": {\n"
                + "    \"origin\": \"runtime\",\n"
                + "    \"raw_path\": \"raw/data/create/recipes/mixing/example.json\",\n"
                + "    \"serializer\": \"create:mixing\",\n"
                + "    \"warnings\": []\n"
                + "  }\n"
                + "}\n";
    }

    private static String exampleTag() {
        return "{\n"
                + "  \"schema_version\": 1,\n"
                + "  \"id\": \"forge:plates/iron\",\n"
                + "  \"values\": [\n"
                + "    \"minecraft:iron_ingot\"\n"
                + "  ]\n"
                + "}\n";
    }
}
